### ISSUE TITLE
Decode error for `get_match_timeline`

### ISSUE THREAD

**Issue by deklanw** [MingweiSamuel/Riven#10]
```
thread 'tokio-runtime-worker' panicked at 'Game KR 4416790570: RiotApiError { reqwest_error: reqwest::Error { kind: Decode, source: Error("missing field `laneType`", line: 1, column: 3758) }, retries: 0, response: None, status_code: Some(200) }', src/grabbing.rs:107:33
```

Seems to be erroring for every game

**Comment by MingweiSamuel** [comment]
Thanks for the report, I'll get it fixed in the hour

**Comment by MingweiSamuel** [comment]
Fix will be at https://crates.io/crates/riven/1.3.1 once it finished uploading

### Bookkeeping

Commit
https://github.com/MingweiSamuel/Riven/commit/33cec4c395476d70eeb76857aab831b701eb922f

Schema
gh-pages https://github.com/MingweiSamuel/riotapi-schema/commit/a9019adde74f372f135c29e757cddeab0560e722
https://github.com/MingweiSamuel/riotapi-schema/commit/f0640a8ebe684568c21ed3dc814d18dd60b2d147
https://github.com/MingweiSamuel/riotapi-schema/commit/063a20d2be23966ca4e6c9fdc61bebc7b8ca851b
