### ISSUE TITLE
`UNRANKED` equivalent for Division?

### ISSUE THREAD

**Issue by deklanw** [MingweiSamuel/Riven#12]
You added an `UNRANKED` variant to the Tier enum, but there is no equivalent for the Division enum. This is a bit awkward. I'm working with a 

```rust

struct RankStuff {
   tier: Tier,
   division: Option<Division>
}

```

Also, as a side note, how did you choose the `u8` values for the Tier enum?

**Comment by MingweiSamuel** [comment]
Yeah I tried a few different things to avoiding adding an UNRANKED tier but my main goals are to closely match Riot's API and avoid manual maintenance.

Personally I would keep `(Tier, Division)` both required and have an UNRANKED tier imply unranked regardless of division, and use `(Tier::UNRANKED, Division::I)`.
There are a few other edge cases to consider with apex tiers, they are all technically `Division::I` so `(Tier::CHALLENGER, Division::III)` is invalid.  
There are a few rank utilities in https://docs.rs/riven/1.4.0/riven/consts/ranks/index.html that could be expanded on to make dealing with ranks easier. Open to suggestions/PRs.

And the `u8` values are completely arbitrary and follow semantic versioning (won't change). In the past I have used consecutive values from zero but then grandmaster threw a wrench in that so I spaced them out to future-proof that. Might have gone a bit overboard with the spacing though.

**Comment by deklanw** [comment]
I see. That all makes sense to me.

I realized I had other things to change with these enums so I just ended up copy-and-pasting your definitions and changing them for my code. Not totally sure if that's advisable in the end, but for now it's working.

Thanks

**Comment by MingweiSamuel** [comment]
Sure. Out of curiosity, what changes did you make?

**Comment by deklanw** [comment]
Well, I'm using sqlx. Turns out that postgres doesn't support unsigned integers, so it's more convenient for them to be signed. Also, I wanted to derive `sqlx::Type` to make everything more seamless. 

Also, for my own purposes I wanted to assign a rank to every game; the median rank works well. But, for that I can't have gaps in the integer representation
