### ISSUE TITLE
Fix tutorial

### ISSUE THREAD

**Issue by adv0cat** [MingweiSamuel/Riven#13]
Hi,
Your tutorial has a `for (i, mastery) in masteries[..10].iter().enumerate()`, but this option would be better `for (i, mastery) in masteries.iter().take(10).enumerate()`. Because if the array does not contain 10 elements, there will be a panic for exiting the range :)

**Comment by MingweiSamuel** [comment]
Good catch. Would you like to submit a pull request? :)
Or I can fix it :)

**Comment by MingweiSamuel** [comment]
Closed by #23
