### ISSUE TITLE
Decode error in `get_match` when some participants are bots

### ISSUE THREAD

**Issue by IcyDefiance** [MingweiSamuel/Riven#17]
RiotApiError {
        reqwest_error: reqwest::Error {
            kind: Decode,
            source: Error("missing field `summonerId`", line: 1, column: 27627)
        },
        retries: 0,
        response: None,
        status_code: Some(200)
    }

This happened to me when requesting match id 3251803350 in NA. The participant identities for the bots don't have a summonerId field.

**Comment by MingweiSamuel** [comment]
Thanks for the report, I’ll publish a fixed version tonight

**Comment by MingweiSamuel** [comment]
Alright, version 1.7.0 released: https://crates.io/crates/riven/1.7.0

I've also created https://github.com/RiotGames/developer-relations/issues/344 since this API response seems pretty silly
