### ISSUE TITLE
[TFT] UnitDto occasionally has extra field 'chosen'

### ISSUE THREAD

**Issue by whyando** [MingweiSamuel/Riven#20]
Riot has recently added an extra field on the unitDto
Here is an extract from
https://europe.api.riotgames.com/tft/match/v1/matches/EUW1_4899709674
`"units":[{"character_id":"TFT4_Maokai","items":[],"name":"","rarity":0,"tier":2},{"character_id":"TFT4_Sylas","chosen":"Set4_Brawler","items":[],"name":"","rarity":1,"tier":2},{"character_id":"TFT4_Vi","items":[],"name":"","rarity":1,"tier":2},{"character_id":"TFT4_Nunu","items":[57],"name":"","rarity":2,"tier":2},{"character_id":"TFT4_Kindred","items":[39,22,23],"name":"","rarity":2,"tier":2},{"character_id":"TFT4_Warwick","items":[],"name":"","rarity":3,"tier":2},{"character_id":"TFT4_Ashe","items":[69,11,16],"name":"","rarity":3,"tier":1}]`

Unfortunately riot haven't documented this in their official docs.

Super hyped to get this data

**Comment by MingweiSamuel** [comment]
1.10.2 will be released momentarily
https://crates.io/crates/riven/1.10.2
