### ISSUE TITLE
Support for new tft-league endpoint /tft/league/v1/rated-ladders/{queue}/top

### ISSUE THREAD

**Issue by whyando** [MingweiSamuel/Riven#24]
![image](https://user-images.githubusercontent.com/934217/117576319-6db87c00-b0dd-11eb-8ad8-287df96ce72b.png)

The final endpoint is new `/tft/league/v1/rated-ladders/{queue}/top` and not yet supported by riven.
It's for the new hyper roll gamemode

**Comment by MingweiSamuel** [comment]
Fixed in https://crates.io/crates/riven/1.12.0 :)

**Comment by whyando** [comment]
Brill thanks!
