### ISSUE TITLE
u16 seems insufficient to represent champion id

### ISSUE THREAD

**Issue by Ploppz** [MingweiSamuel/Riven#36]
Example match: `EUW1_5102203800`. I used https://developer.riotgames.com/apis#match-v5/GET_getMatch and the response has a field:

```
                "championId": 37225015,
```
But `riven` throws an error:

```
Client(
    Error {
        context: "Error in get_match",
        source: RiotApiError {
            reqwest_error: reqwest::Error {
                kind: Decode,
                source: Error("invalid value: integer `37225015`, expected i16", line: 1, column: 1254),
            },
            retries: 0,
            response: None,
            status_code: Some(
                200,
            ),
        },
    },
)
```

**Comment by MingweiSamuel** [comment]
This is this issue: https://github.com/RiotGames/developer-relations/issues/553

probably best to add a custom deserializer to handle this case so it will still parse

**Comment by MingweiSamuel** [comment]
Mitigated in 2.5.0, you can now use `participant.champion()` to recover the champion/ID: https://docs.rs/riven/2.5.0/riven/models/match_v5/struct.Participant.html#method.champion
