### ISSUE TITLE
How do I handle users inputting invalid summoner names?

### ISSUE THREAD

**Issue by ghost** [MingweiSamuel/Riven#40]
Hi there,
whenever a user inputs a invalid summoner name my entire app crashes because you are supposed to use except for error handeling? In my specific case it's :

`    let summoner = &ctx.data().riot_api.summoner_v4()
        .get_by_summoner_name(region, &name).await
        .expect("Something went wrong")
        .expect("Something went wrong");
`

How do I fix that? It's code within an async method, so I have really no clue how to handle it due to me being entirely new to rust.

**Comment by MingweiSamuel** [comment]
The outermost `Result` is errored if some API error occurred. The inner `Option` relates to whether the user exists or not

So the following would be an improvement:
```rust
let summoner_result = &ctx.data().riot_api.summoner_v4() .get_by_summoner_name(region, &name).await;
let summoner_opt = summoner_result.expect("An API error occurred"); // TODO: handle this gracefully.
if let Some(summoner) = summoner_opt {
  println!("Summoner {} was found!", summoner.name);
}
else {
  println!("Summoner not found!");
}
```
