### ISSUE TITLE
Error getting TFT games

### ISSUE THREAD

**Issue by GuillerLT** [MingweiSamuel/Riven#50]
API: tft_match_v1 / get_match
"error decoding response body: missing field `items` at line 1 column 2493"

**Comment by MingweiSamuel** [comment]
Looking in to it, do you have a specific match ID? Or does this seem to happen consistently?

**Comment by MingweiSamuel** [comment]
Found a few undocumented fields: https://github.com/RiotGames/developer-relations/issues/749

**Comment by GuillerLT** [comment]
It was pretty consistent today, some examples
EUW1_6307427444
EUW1_6307262798
EUW1_6307189278
EUW1_6307128369
EUW1_6307054496
EUW1_6306984191
EUW1_6306939631
EUW1_6306890128
EUW1_6306805268
EUW1_6306775958
EUW1_6306739613
EUW1_6306698403
EUW1_6306678360
EUW1_6306663673

**Comment by MingweiSamuel** [comment]
Fixed in 2.13.0 https://crates.io/crates/riven/2.13.0
