### ISSUE TITLE
Add arena game mode

### ISSUE THREAD

**Issue by shinobu-uwu** [MingweiSamuel/Riven#59]
Since arena game mode is out when trying to retrieve a match from it I get this error
`RiotApiError { reqwest_error: reqwest::Error { kind: Decode, source: Error("invalid value: 0, expected one of: 100, 200, 300", line: 1, column: 27238) }, retries: 0, response: None, status_code: Some(200) }`

**Comment by MingweiSamuel** [comment]
What version of riven? Should be fixed in `2.22.0`

**Comment by shinobu-uwu** [comment]
:thinking: I am running version `2.22.0`, if I enter the puuid `oGnFuEylQMJneeQPal1umHASfeB7cydH_sxvupPm71adQX1RTWA7O_KfjjGlZ5OA2kikTW30sF551A` on NA in the code below I get the error I pasted here previously, which I assume is due to the arena gamemode

```rs
#[tauri::command]
async fn get_summoner_history(id: &str, region: &str) -> Result<Vec<Match>, String> {
    let region = PlatformRoute::from_str(region).map_err(|e| e.to_string())?;
    let api_key = REDACTED;
    let api = RiotApi::new(api_key);
    let ids = api
        .match_v5()
        .get_match_ids_by_puuid(
            region.to_regional(),
            id,
            Some(10),
            None,
            None,
            None,
            None,
            None,
        )
        .await
        .map_err(|e| e.to_string())?;
    let mut matches = Vec::new();

    for id in ids {
        let match_data = api
            .match_v5()
            .get_match(region.to_regional(), id.as_str())
            .await.unwrap();
            // .map_err(|e| e.to_string())?;

        if let Some(m) = match_data {
            matches.push(m);
        }
    }

    Ok(matches)
}
```

**Comment by MingweiSamuel** [comment]
What's the username and region of that player? PUUIDs are unique per API app

**Comment by shinobu-uwu** [comment]
`Bang Fangirl` (:facepalm:) on `NA`

**Comment by MingweiSamuel** [comment]
Ok, seems like v2.22.0 didn't actually contain the changes it was supposed to. So v2.23.0 is released now which should work

**Comment by shinobu-uwu** [comment]
It works now, thanks!
