### ISSUE TITLE
Metadata field can be null in `TournamentV5::get_games()`

### ISSUE THREAD

**Issue by sadroad** [MingweiSamuel/Riven#61]
When querying `TournamentV5::get_games()`, the method always attempts to decode the metadata field even when it's omitted. 
This leads to the following error:
![image](https://github.com/MingweiSamuel/Riven/assets/30816242/802ad123-a403-48d1-bbc4-977154d864d9)

This is due to the field being required in [OpenAPI spec](https://github.com/MingweiSamuel/Riven/blob/406df5188fa70935b8783a7cbc7da93c4f75e97a/riven/srcgen/index.js#L14C3-L17C5) used to generate the code.

On the Riot docs for the [endpoint](https://developer.riotgames.com/apis#tournament-v5/GET_getGames), the field isn't noted to be optional, but if removed from the body during tournament code creation, it's not returned.

**Comment by MingweiSamuel** [comment]
Is it possible to repro in tournament-stub?

**Comment by MingweiSamuel** [comment]
I guess not since that DTO doesn't exist in stub

**Comment by MingweiSamuel** [comment]
Fixed in https://crates.io/crates/riven/2.30.0 though there may be other such issues as the tournament apis aren't very well tested
