### ISSUE TITLE
Some matches have PascalCasing for ParticipantMissions.

### ISSUE THREAD

**Issue by jsdt** [MingweiSamuel/Riven#65]
It looks like some matches have version 14.6 for some reason (despite it not being released), and these matches are using PascalCase for the fields in `ParticipantMissions` for the match v5 endpoint response. It seems like an alias is needed to make parsing work for both versions.

I didn't dig into the code generation, but I made some changes locally to get it working. This commit adds the aliases and adds a test with one of the problematic matches: https://github.com/jsdt/Riven/commit/d156223d160f76a536870594da7d25f0635d5254

**Comment by MingweiSamuel** [comment]
Excellent riot spaghetto

**Comment by MingweiSamuel** [comment]
`TH2_24825892`

**Comment by MingweiSamuel** [comment]
Not sure how I'll represent this inconsistency-ness in https://github.com/MingweiSamuel/riotapi-schema (https://stackoverflow.com/questions/21970210/json-schema-property-aliasing) but will be easy to incorporate the serde fix into the codegen when I figure it out

**Comment by MingweiSamuel** [comment]
Fixed in c00c8abace34b5a22044bf674bd598d677192ab6 c0355495f51f163bf57bf712ee30b3b3af72a257 released 2.37.0
