### ISSUE TITLE
match-v5 ChallengesDto's field "bountyGold" is incorrectly documented as an int when it can be a float [upstream]

### ISSUE THREAD

**Issue by NotTheEconomist** [MingweiSamuel/Riven#74]
Just a bit of a note to drive development if and when Riot fixes the API documentation. Looks like `bountyGold` in the ChallengesDto is incorrectly documented as an int while it can return a float.

Upstream issue: https://github.com/RiotGames/developer-relations/issues/1005

Repro steps:

```
let api = RiotApi::new(MY_API_KEY);
let match_id = "NA1_5145391102";
api.match_v5().get_match(PlatformRoute::NA1.to_regional(), match_id).await.expect("This will panic!")
```

**Comment by MingweiSamuel** [comment]
Fixed in 381db0feff194f746112a5be29c5c34f92488489 released Riven 2.57.0
