### ISSUE TITLE
TFT Trait Decode error: "missing field `tier_total`"

### ISSUE THREAD

**Issue by whyando** [MingweiSamuel/Riven#8]
`let game = riot_api.tft_match_v1().get_match(Region::EUROPE, "EUW1_4571378004").await.expect("Get match failed.");`

`thread 'main' panicked at 'Get match failed.: RiotApiError { reqwest_error: reqwest::Error { kind: Decode, source: Error("missing field `tier_total`", line: 1, column: 5235) }, retries: 0, response: None, status_code: Some(200) }', src/main.rs:10:16`

Not every request fails, but quite a large amount do, including:
EUW1_4568680990
EUW1_4568595387
EUW1_4568448008
EUW1_4568443707
EUW1_4568396630
EUW1_4570765723
EUW1_4570647555

The culprit seems to be this bizarre trait which pops up every so often:
`{
    "name": "TemplateTrait",
    "num_units": 1,
    "style": 0,
    "tier_current": 0
  }`

**Comment by MingweiSamuel** [comment]
Looks to be a field that should be marked `Option` but isn't, should be a quick fix

**Comment by MingweiSamuel** [comment]
Fixed in [1.2.0](https://crates.io/crates/riven/1.2.0).
Also found another issue, all the `tft-summoner-v1.SummonerDTO` fields were `Option`s when they should all be required, also fixed, so you can have a few less `.unwraps()`.
