### ISSUE TITLE
Missing tft field "game_variation"

### ISSUE THREAD

**Issue by whyando** [MingweiSamuel/Riven#9]
The field is missing from here: https://docs.rs/riven/1.2.0/riven/models/tft_match_v1/struct.Info.html

I'm not sure if it needs be an option, perhaps for backwards compatibility

sample from riot 
```
"info": {
        "game_datetime": 1587749742531,
        "game_length": 2275.833984375,
        "game_variation": "TFT3_GameVariation_BigLittleLegends",
        "game_version": "Version 10.8.317.8137 (Apr 17 2020/16:09:11) [PUBLIC] <Releases/10.8>",
        "participants": [       ...
```

Currently the field is just discarded

**Comment by whyando** [comment]
it's not in the riot docs either!
https://developer.riotgames.com/apis#tft-match-v1/GET_getMatch

**Comment by MingweiSamuel** [comment]
You can make an issue for Riot here: https://github.com/RiotGames/developer-relations/issues/new?assignees=&labels=&template=bug_report.md&title=%5BBUG%5D%5BDOCS%5D+

I'll just need to add a patch to https://github.com/MingweiSamuel/riotapi-schema and rebuild to fix on this end, will be a half hour

It does seem that older matches didn't have this field (i.e. `PBE1_4328907912`, really old) so it will be an Option.

**Comment by whyando** [comment]
wow brilliant thanks, I've submitted an issue for riot.

would it help you out if I gathered some recent outputs for every tft api?

**Comment by MingweiSamuel** [comment]
Alright there we go: https://docs.rs/riven/1.3.0/riven/models/tft_match_v1/struct.Info.html#structfield.game_variation

> would it help you out if I gathered some recent outputs for every tft api?

Might be worth making https://github.com/MingweiSamuel/riotapi-schema/ do some example-based schema generation given the flaky docs. I also wish I could run TFT endpoints on CI, but currently I can't get a TFT api key. For now I don't have any use for recent outputs.
